from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
BACKEND_SRC = ROOT / "backend" / "src"
GENERATED_TYPES_END = "export interface MirrorCapabilityState"
GENERATED_HEADER = "// <auto-generated by scripts/generate_account_contracts.py>\n"
GENERATED_FOOTER = "// </auto-generated>\n\n"

if str(BACKEND_SRC) not in sys.path:
    sys.path.insert(0, str(BACKEND_SRC))

from nautilus_account_console.schemas import (  # noqa: E402
    AccountEvent,
    AccountKind,
    AccountSnapshot,
    OrderEvent,
    OrderExecutionReports,
)


SCHEMA_TARGETS = {
    "account_snapshot.schema.json": AccountSnapshot,
    "account_event.schema.json": AccountEvent,
    "order_event.schema.json": OrderEvent,
}

TS_MODELS = (
    ("AccountSnapshot", AccountSnapshot),
    ("AccountEvent", AccountEvent),
    ("OrderEvent", OrderEvent),
    ("OrderExecutionReports", OrderExecutionReports),
)


def _json_schema_for(model: type[Any], filename: str) -> str:
    schema = model.model_json_schema()
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://nautilus.local/contracts/{filename}",
        **schema,
        "additionalProperties": False,
    }
    return json.dumps(schema, ensure_ascii=False, indent=2) + "\n"


def _field_ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        if schema["$ref"] == "#/$defs/AccountKind":
            return "AccountKind"
        if schema["$ref"] == "#/$defs/OrderEvent":
            return "OrderEvent"
        return "Record<string, unknown>"
    if "anyOf" in schema:
        variants = [_field_ts_type(item) for item in schema["anyOf"]]
        deduped = list(dict.fromkeys(variants))
        return " | ".join(deduped)
    json_type = schema.get("type")
    if json_type == "string":
        return "string"
    if json_type in {"integer", "number"}:
        return "number"
    if json_type == "boolean":
        return "boolean"
    if json_type == "array":
        item_type = _field_ts_type(schema.get("items", {}))
        return f"{item_type}[]"
    if json_type == "object":
        return "Record<string, unknown>"
    if json_type == "null":
        return "null"
    return "unknown"


def _ts_interface(name: str, model: type[Any]) -> str:
    schema = model.model_json_schema()
    properties = schema.get("properties", {})
    lines = [f"export interface {name} {{"]
    for field_name, field_schema in properties.items():
        lines.append(f"  {field_name}: {_field_ts_type(field_schema)};")
    lines.append("}")
    return "\n".join(lines)


def _generated_types_prefix() -> str:
    account_values = [f'  | "{item.value}"' for item in AccountKind]
    account_kind = "export type AccountKind =\n" + "\n".join(account_values) + ";\n"
    interfaces = "\n\n".join(_ts_interface(name, model) for name, model in TS_MODELS)
    return GENERATED_HEADER + account_kind + "\n" + interfaces + "\n" + GENERATED_FOOTER


def _render_types_ts() -> str:
    path = ROOT / "frontend" / "src" / "types.ts"
    existing = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    marker_index = existing.find(GENERATED_TYPES_END)
    if marker_index == -1:
        raise SystemExit(f"missing TypeScript continuation marker: {GENERATED_TYPES_END}")
    suffix = existing[marker_index:]
    return (_generated_types_prefix() + suffix).replace("\r\n", "\n")


def _expected_outputs() -> dict[Path, str]:
    outputs = {
        ROOT / "frontend" / "src" / "types.ts": _render_types_ts(),
    }
    for filename, model in SCHEMA_TARGETS.items():
        outputs[ROOT / "contracts" / filename] = _json_schema_for(model, filename)
    return outputs


def _repo_relative(path: Path) -> str:
    return Path(os.path.relpath(path, ROOT)).as_posix()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated contract files are stale")
    args = parser.parse_args(argv)

    stale: list[str] = []
    for path, expected in _expected_outputs().items():
        current = path.read_bytes().decode("utf-8") if path.exists() else ""
        if current != expected:
            stale.append(_repo_relative(path))
            if not args.check:
                path.write_bytes(expected.encode("utf-8"))

    if stale and args.check:
        print("ACCOUNT_CONTRACT_CODEGEN_STALE")
        for item in stale:
            print(f"STALE: {item}")
        return 1

    if stale:
        print("ACCOUNT_CONTRACT_CODEGEN_WRITTEN")
        for item in stale:
            print(f"WRITTEN: {item}")
    else:
        print("ACCOUNT_CONTRACT_CODEGEN_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
